### ISSUE TITLE
Error integrating ui-extension

### ISSUE THREAD

**Issue by asiz15** [Tyratox/vendure-product-recommendations#28]
Hi!
I have installed the plugin and works as expected, but when I try to integrate the ui-extension I am getting the following errors when entering the admin.

![Screenshot_12](https://user-images.githubusercontent.com/13662081/138576632-f1d00115-4beb-404d-aa9f-e99aca14b37f.png)
The console does not show any errors and the build seems to be ok.

![Screenshot_13](https://user-images.githubusercontent.com/13662081/138576665-2dac3ef2-3237-41fc-b08c-c912ef84c483.png)

this is my vendure-config file:

![Screenshot_14](https://user-images.githubusercontent.com/13662081/138576687-47defc01-31f7-4afe-a11e-8371e8faad69.png)

What im doing wrong?

**Comment by Tyratox** [comment]
Hi, thank you for reporting this. As I have stopped using the UI part of the plugin (I've started integrating it into the frontend directly), I didn't update it anymore and it seems as if the GraphQL schema has changed. I think I'll remove the UI extension from the repository as I currently do not plan to keep updating it. I'm sorry for that! But you are welcome to fix the issue in the fork you have created, probably it's only a matter of updating the GraphQL queries.
