### ISSUE TITLE
ng build --prod error for UI with another plugin

### ISSUE THREAD

**Issue by BeepLoveKarki** [Tyratox/vendure-product-recommendations#3]
I tried this and your bulk discount plugin together for my UI extensions, but when I use them together, I get a lot of errors.

But when I use them singly or just run ng build, error occurs. ng build --prod gives error.

**Comment by Tyratox** [comment]
Interesting. To be honest I haven't tested a production build yet as I'm still developing the system but in development mode everything seems to work for me. Does it work when run in development mode, i.e. just `npm start` / `yarn start` in the vendure directory?

Also could you please post the error message together with your vendure config (at least the relevant parts, i.e. the admin ui part)? Without the given information I can't help you, I'm sorry.

**Comment by Tyratox** [comment]
Oh, just saw the slack messages 😅

**Comment by BeepLoveKarki** [comment]
After all research I found that your product recommendations plugin is not production ready as per the UI extension. Bulk discounts ones is perfectly fine.

**Comment by Tyratox** [comment]
Fixed in the new release on npm. Thank you!
